/**
 * Validate the structural integrity of a Claude Code memory directory.
 *
 * Checks:
 *   1. MEMORY.md exists and is within Claude Code's session-start
 *      load budget: ≤200 lines AND ≤25KB. The optional cold-tier index
 *      MEMORY-archive.md is NOT counted against this budget — it is read
 *      on demand, not at session start.
 *   2. Every .md file in the memory dir (except MEMORY.md,
 *      MEMORY-archive.md, edges.json) is REACHABLE from MEMORY.md /
 *      MEMORY-archive.md — either directly referenced (a working-set or
 *      archive index line) OR covered by a region pointer's glob. This
 *      replaces the old enumerate-every-file "no orphans" rule, so the
 *      eagerly-loaded working set can stay bounded as total memory grows
 *      (Stage 1 of the cross-store memory redesign). "Present on disk"
 *      alone is NOT reachable — the check would be vacuous.
 *   3. Every file directly referenced in either index exists on disk
 *      (no broken references), AND every region pointer's glob matches at
 *      least one on-disk file (no stale/confidently-wrong region cues —
 *      region pointers are derived from contents, never authoritative).
 *   4. Topic-style files (migrated from omega) and MEMORY-archive.md do
 *      not exceed 50KB. Per-file curated style: no size cap.
 *
 * Wired into /validate via templates/skills/validate/phases/validators.md.
 * Also runs PostToolUse on memory-dir writes via
 * templates/.claude/hooks/memory-index-guard.sh.
 *
 * Exit codes:
 *   0 — pass
 *   1 — one or more violations
 *   2 — bad usage / inaccessible memory dir
 *
 * @module scripts/validate-memory
 */

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { resolveMemoryDir } = require('./project-context.cjs');

const MEMORY_INDEX_FILE = 'MEMORY.md';
// Cold-tier index: holds curated entries spilled out of the hot index so
// the session-start load budget stays small. Read on demand (MEMORY.md
// links to it), never loaded automatically — so it is exempt from the hot
// line/byte caps and bounded only by the 50KB topic-file cap.
const MEMORY_ARCHIVE_FILE = 'MEMORY-archive.md';
const MEMORY_INDEX_LINE_CAP = 200;
const MEMORY_INDEX_BYTE_CAP = 25_000;
const TOPIC_FILE_SIZE_CAP = 50_000;
const NON_MEMORY_FILES = new Set([
  'MEMORY.md',
  'MEMORY-archive.md',
  'edges.json',
  '.DS_Store',
]);

// Files that match this pattern are "topic-style" (multi-memory files
// produced by Phase 1 migration). The 50KB cap applies to them.
// Per-file curated style files (one memory each) are not size-capped.
const TOPIC_FILE_NAMES = new Set([
  'decisions.md',
  'lessons.md',
  'preferences.md',
  'constraints.md',
  'session-summaries.md',
  'subagent-residue.md',
  'unscoped.md',
]);
const TOPIC_FILE_PATTERNS = [
  /^(decisions|lessons|preferences|constraints|session-summaries|subagent-residue|unscoped)(-recent|-archive)?(-\d+)?\.md$/,
  /^cross-[a-z0-9_-]+(-recent|-archive)?(-\d+)?\.md$/,
];

function isTopicStyleFile(name) {
  if (TOPIC_FILE_NAMES.has(name)) return true;
  return TOPIC_FILE_PATTERNS.some((re) => re.test(name));
}

/**
 * Extract all `.md` filenames referenced from MEMORY.md.
 * Handles both index formats:
 *   - Topic-files: `- **decisions.md** (56 entries) — desc`
 *   - Curated:    `- [Title](file.md) — desc`
 */
function parseMemoryIndex(memoryMdText) {
  const refs = new Set();
  // Topic-files format: bolded filename
  for (const m of memoryMdText.matchAll(/\*\*([a-z0-9_.-]+\.md)\*\*/gi)) {
    refs.add(m[1]);
  }
  // Curated format: markdown link
  for (const m of memoryMdText.matchAll(/\]\(([a-z0-9_.-]+\.md)\)/gi)) {
    refs.add(m[1]);
  }
  return refs;
}

/**
 * Parse region pointers from an index file. A region pointer declares
 * that a whole CLASS of files is reachable without each having its own
 * index line — the cue-based-retrieval tier that lets the eagerly-loaded
 * working set stay bounded as total memory grows. Format (the
 * backtick-quoted glob is the only part the validator reads):
 *
 *   - region `lesson_*.md` → [MEMORY-archive.md](MEMORY-archive.md) — 98 lessons; grep the archive
 *
 * Returns [{ glob, raw }]. Region pointers are DERIVED from actual
 * contents (regenerated by the consolidation pass / by hand from what's
 * on disk), never authoritative — so a glob matching nothing on disk is
 * a stale, confidently-wrong cue and fails validation (see below).
 */
export function parseRegionPointers(text) {
  const pointers = [];
  for (const m of text.matchAll(/^[\s>]*-\s*region\s+`([^`]+)`/gim)) {
    pointers.push({ glob: m[1].trim(), raw: m[0].trim() });
  }
  return pointers;
}

/**
 * Translate a shell-style glob (only `*` and `?` are special) into an
 * anchored, case-sensitive RegExp matching a bare filename.
 */
export function globToRegex(glob) {
  const escaped = glob
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*/g, '.*')
    .replace(/\?/g, '.');
  return new RegExp(`^${escaped}$`);
}

/**
 * Reachability is the Stage-1 invariant that REPLACES enumeration: a
 * file need not have its own index line, but it MUST be findable from
 * MEMORY.md — either directly referenced (working-set/archive line) or
 * covered by a region pointer's glob. "Present on disk" alone is NOT
 * reachable (it would make the check vacuous — every file is grep-able).
 */
export function isReachable(name, referenced, regionRegexes) {
  if (referenced.has(name)) return true;
  return regionRegexes.some((re) => re.test(name));
}

/**
 * Validate one memory directory.
 *
 * @returns {{ violations: string[], warnings: string[], stats: object }}
 */
export function validateMemoryDir(opts = {}) {
  const memoryDir = opts.memoryDir
    ? path.resolve(opts.memoryDir)
    : resolveMemoryDir({ homeDir: opts.homeDir, cwd: opts.cwd, settingsPath: opts.settingsPath });

  const violations = [];
  const warnings = [];
  const stats = { memoryDir };

  if (!fs.existsSync(memoryDir)) {
    return {
      violations: [`memory directory does not exist: ${memoryDir}`],
      warnings,
      stats,
    };
  }

  const indexPath = path.join(memoryDir, MEMORY_INDEX_FILE);
  if (!fs.existsSync(indexPath)) {
    return {
      violations: [`${MEMORY_INDEX_FILE} missing under ${memoryDir}`],
      warnings,
      stats,
    };
  }

  const indexText = fs.readFileSync(indexPath, 'utf8');
  const indexBytes = Buffer.byteLength(indexText, 'utf8');
  const indexLines = indexText.split('\n').length;
  stats.indexLines = indexLines;
  stats.indexBytes = indexBytes;

  if (indexLines > MEMORY_INDEX_LINE_CAP) {
    violations.push(
      `MEMORY.md exceeds line cap: ${indexLines} lines (max ${MEMORY_INDEX_LINE_CAP}). Reduce index verbosity or move details into topic files.`
    );
  }
  if (indexBytes > MEMORY_INDEX_BYTE_CAP) {
    violations.push(
      `MEMORY.md exceeds byte cap: ${indexBytes} bytes (max ${MEMORY_INDEX_BYTE_CAP}). Reduce index verbosity.`
    );
  }

  // Cold-tier archive (optional). Its references count toward the
  // "no orphans" check exactly like the hot index's, so spilling an entry
  // into the archive doesn't orphan its file — but it is NOT subject to
  // the hot line/byte caps (it's read on demand, not at session start).
  const archivePath = path.join(memoryDir, MEMORY_ARCHIVE_FILE);
  const hasArchive = fs.existsSync(archivePath);
  const archiveText = hasArchive ? fs.readFileSync(archivePath, 'utf8') : '';

  const hotRefs = parseMemoryIndex(indexText);
  const referenced = new Set(hotRefs);
  if (hasArchive) {
    for (const ref of parseMemoryIndex(archiveText)) referenced.add(ref);
    const archiveBytes = Buffer.byteLength(archiveText, 'utf8');
    stats.archiveBytes = archiveBytes;
    if (archiveBytes > TOPIC_FILE_SIZE_CAP) {
      violations.push(
        `${MEMORY_ARCHIVE_FILE} exceeds size cap: ${archiveBytes} bytes (cap ${TOPIC_FILE_SIZE_CAP}). Re-shard the archive or split it.`
      );
    }
    // No silent invisibility: an archive the hot index doesn't link to is
    // unreachable at session start. Warn (not fail) — the entries are
    // still valid, just undiscoverable until MEMORY.md points at them.
    if (!hotRefs.has(MEMORY_ARCHIVE_FILE)) {
      warnings.push(
        `${MEMORY_ARCHIVE_FILE} exists but MEMORY.md does not link to it — archived memories won't be discoverable at session start. Add a [${MEMORY_ARCHIVE_FILE}](${MEMORY_ARCHIVE_FILE}) pointer in MEMORY.md.`
      );
    }
  }
  stats.indexedFileCount = referenced.size;

  // Region pointers come from EITHER index tier (hot or cold). They are
  // the bounded-index mechanism: a class of files reachable without one
  // line each.
  const regionPointers = [
    ...parseRegionPointers(indexText),
    ...(hasArchive ? parseRegionPointers(archiveText) : []),
  ];
  const regionRegexes = regionPointers.map((p) => globToRegex(p.glob));
  stats.regionPointerCount = regionPointers.length;

  const entries = fs.readdirSync(memoryDir).filter((f) => !f.startsWith('.'));
  const onDiskMd = entries.filter((f) => f.endsWith('.md') && !NON_MEMORY_FILES.has(f));
  stats.onDiskMemoryFileCount = onDiskMd.length;

  // Reachability check (replaces enumeration): a file is an orphan only
  // when NOTHING makes it findable from MEMORY.md — no index line AND no
  // region pointer covers it. A directly-indexed file or one matched by a
  // region glob is reachable and fine.
  for (const f of onDiskMd) {
    if (!isReachable(f, referenced, regionRegexes)) {
      violations.push(
        `orphan memory file: ${f} exists in ${memoryDir} but is not reachable from MEMORY.md — ` +
          `it has no index line (**${f}** bold or [text](${f}) link) and no region pointer matches it. ` +
          `Add a working-set/archive line (via /cc-remember), add a covering region pointer, or delete it. ` +
          `("Present on disk" alone does NOT count as reachable.)`
      );
    }
  }

  // Stale region pointers: a glob that matches no file on disk is a
  // dangling, confidently-wrong retrieval cue (worse than no map). Region
  // pointers are derived from contents — regenerate or remove.
  for (const p of regionPointers) {
    const re = globToRegex(p.glob);
    if (!onDiskMd.some((f) => re.test(f))) {
      violations.push(
        `stale region pointer: \`${p.glob}\` matches no files on disk in ${memoryDir}. ` +
          `Region pointers are derived from actual contents — regenerate it from what's present or remove it.`
      );
    }
  }

  // Per-write hook mode: answer "is THIS just-written file reachable?"
  // The memory-index-guard hook keys solely on this so relaxing the
  // enumeration rule doesn't silently retire the guard.
  if (opts.checkFile) {
    stats.checkFile = path.basename(opts.checkFile);
    // The index files themselves (MEMORY.md, MEMORY-archive.md, edges.json)
    // are not memory entries — they are never "reachable from MEMORY.md" by
    // definition, and the full-validation orphan check already excludes them
    // via NON_MEMORY_FILES. Mirror that exclusion here, or the per-write
    // guard nags on every edit to the index itself ("MEMORY.md is not
    // reachable from MEMORY.md").
    stats.checkFileReachable = NON_MEMORY_FILES.has(stats.checkFile)
      ? true
      : isReachable(stats.checkFile, referenced, regionRegexes);
  }

  // Broken references (indexed but missing on disk).
  for (const ref of referenced) {
    if (ref === MEMORY_INDEX_FILE) continue;
    if (!entries.includes(ref)) {
      violations.push(
        `broken reference in MEMORY.md: ${ref} is indexed but does not exist on disk. ` +
          `(References are parsed from **name.md** / [text](name.md) tokens — a partial or ` +
          `abbreviated name inside those forms parses as a reference to a file that isn't there.)`
      );
    }
  }

  // Size cap on topic-style files.
  for (const f of onDiskMd) {
    if (!isTopicStyleFile(f)) continue;
    const bytes = fs.statSync(path.join(memoryDir, f)).size;
    if (bytes > TOPIC_FILE_SIZE_CAP) {
      violations.push(
        `topic file too large: ${f} is ${bytes} bytes (cap ${TOPIC_FILE_SIZE_CAP}). Re-shard via migration tool or split manually.`
      );
    }
  }

  return { violations, warnings, stats };
}

// --- Stage-1 instrumentation: spill-rate sampler -------------------------
// Records how often the eagerly-loaded working set runs near its budget,
// so Stage 2 (lifecycle verbs + forcing function) is gated on a MEASURED
// pressure signal, not on a felt "the index keeps overflowing" metaphor.
// Append-only, at most one sample per day, only when utilization is high.
// Lives at `<memoryDir>/.memory-pressure.jsonl` (a dotfile — invisible to
// the orphan scan, which skips dot-prefixed entries).
const PRESSURE_LOG = '.memory-pressure.jsonl';
const PRESSURE_THRESHOLD = 0.9;

export function recordPressureSample(memoryDir, stats, now = new Date()) {
  if (stats.indexLines === undefined || stats.indexBytes === undefined) return false;
  const util = Math.max(
    stats.indexLines / MEMORY_INDEX_LINE_CAP,
    stats.indexBytes / MEMORY_INDEX_BYTE_CAP
  );
  if (util < PRESSURE_THRESHOLD) return false;
  const logPath = path.join(memoryDir, PRESSURE_LOG);
  const day = now.toISOString().slice(0, 10);
  try {
    if (fs.existsSync(logPath)) {
      const lines = fs.readFileSync(logPath, 'utf8').trim().split('\n');
      const last = lines[lines.length - 1];
      if (last && last.includes(`"date":"${day}"`)) return false; // one/day
    }
    const sample = JSON.stringify({
      date: day,
      lines: stats.indexLines,
      bytes: stats.indexBytes,
      util: Number(util.toFixed(3)),
    });
    fs.appendFileSync(logPath, sample + '\n');
    return true;
  } catch {
    return false; // instrumentation must never break validation
  }
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const args = process.argv.slice(2);
  let memoryDir = null;
  let quiet = false;
  let checkFile = null;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--memory-dir' || args[i] === '--dir') memoryDir = args[++i];
    else if (args[i] === '--quiet') quiet = true;
    else if (args[i] === '--check-file') checkFile = args[++i];
    else if (args[i] === '--help' || args[i] === '-h') {
      console.log('usage: validate-memory.mjs [--memory-dir <path>] [--check-file <path>] [--quiet]');
      console.log('  Validates a Claude Code memory directory. Defaults to the');
      console.log('  current project\'s memory dir. Exits 0 on pass, 1 on violations.');
      console.log('  --check-file: per-write mode — exit 1 only if THAT file is not');
      console.log('  reachable from MEMORY.md (used by the memory-index-guard hook).');
      process.exit(0);
    }
  }
  try {
    const { violations, warnings, stats } = validateMemoryDir({ memoryDir, checkFile });
    // Per-write hook mode: key the exit solely on whether the named file
    // is reachable. A pre-existing unrelated violation must NOT make the
    // guard fire on every write (it would cry wolf), and a reachable fresh
    // write must stay silent.
    if (checkFile) {
      if (stats.checkFileReachable === false) {
        console.error(
          `FAIL: ${stats.checkFile} was written to the memory dir but is not reachable ` +
            `from MEMORY.md (no index line, no covering region pointer).`
        );
        process.exit(1);
      }
      process.exit(0);
    }
    // Default mode (runs in /validate and orient — periodic, not per-write):
    // sample working-set pressure for the Stage-2 gate.
    recordPressureSample(stats.memoryDir, stats);
    if (!quiet) {
      console.log(`memory-dir: ${stats.memoryDir}`);
      if (stats.indexLines !== undefined) {
        console.log(`MEMORY.md:  ${stats.indexLines} lines / ${stats.indexBytes} bytes`);
      }
      if (stats.archiveBytes !== undefined) {
        console.log(`archive:    ${stats.archiveBytes} bytes (cold tier, off the load budget)`);
      }
      if (stats.onDiskMemoryFileCount !== undefined) {
        console.log(`on disk:    ${stats.onDiskMemoryFileCount} files`);
        console.log(`indexed:    ${stats.indexedFileCount} references`);
      }
    }
    for (const w of warnings) console.warn(`WARN: ${w}`);
    for (const v of violations) console.error(`FAIL: ${v}`);
    if (violations.length > 0) {
      console.error(`\nvalidate-memory: ${violations.length} violation(s)`);
      process.exit(1);
    }
    if (!quiet) console.log('validate-memory: PASS');
    process.exit(0);
  } catch (e) {
    console.error('validate-memory failed:', e.message);
    process.exit(2);
  }
}
